// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdjEACFN-OGRAr6EJJ9DJOxT0IG6WXS8E',
    appId: '1:1007630993508:web:1e6f422a58bb064a75b771',
    messagingSenderId: '1007630993508',
    projectId: 'survey-app-6b4b4',
    authDomain: 'survey-app-6b4b4.firebaseapp.com',
    storageBucket: 'survey-app-6b4b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7huYD--r3-QhyoSUc6Oz79xFWvQsi3lw',
    appId: '1:1007630993508:android:3d81271fde50594a75b771',
    messagingSenderId: '1007630993508',
    projectId: 'survey-app-6b4b4',
    storageBucket: 'survey-app-6b4b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1mZYRFyTJfVgd4wsnCdoAcdnqtJ3VsYo',
    appId: '1:1007630993508:ios:48bc8d0b84795c3175b771',
    messagingSenderId: '1007630993508',
    projectId: 'survey-app-6b4b4',
    storageBucket: 'survey-app-6b4b4.firebasestorage.app',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1mZYRFyTJfVgd4wsnCdoAcdnqtJ3VsYo',
    appId: '1:1007630993508:ios:48bc8d0b84795c3175b771',
    messagingSenderId: '1007630993508',
    projectId: 'survey-app-6b4b4',
    storageBucket: 'survey-app-6b4b4.firebasestorage.app',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdjEACFN-OGRAr6EJJ9DJOxT0IG6WXS8E',
    appId: '1:1007630993508:web:30291551c6292fc175b771',
    messagingSenderId: '1007630993508',
    projectId: 'survey-app-6b4b4',
    authDomain: 'survey-app-6b4b4.firebaseapp.com',
    storageBucket: 'survey-app-6b4b4.firebasestorage.app',
  );
}
